---
- name: test
  hosts: "tag_Name_DockerDeploy"
  become: yes

  tasks:
  - name: install docker
    yum: name=docker state=latest
    register: docker_state

  - name: install docker compose
    shell: |
       curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
       chmod +x /usr/bin/docker-compose
    when: docker_state.changed

  - name: add user to docker group
    user: name=ec2-user
          group=docker
          append=yes
    register: user_task

  - name: reset ssh sesions
    meta: reset_connection

  - name: start docker service and enable
    service: name=docker state=started enabled=yes

  - name: build.latest #check if exist
    stat:
      path: build.latest
    register: stat_result

  - name: Copy Files for docker-compose proxy build
    copy:
      src: "{{ dcSource }}"
      dest: /home/ec2-user
      owner: ec2-user
      mode: '0600'

  - name: Clear docker-compose
    shell: build=$(cat build.latest) docker-compose down --rmi all
    when: stat_result.stat.exists

  - name: Start docker-compose
    shell: |
       build={{ repo }}:{{ build  }} docker-compose up -d
       echo {{ repo }}:{{ build }} > build.latest
    register: dc

  - debug: var=dc.stdout_lines
