---
- name: test
  hosts: "tag_Name_DockerDeploy"
  become: yes

  tasks:
  - name: install docker
    yum: name=docker state=latest
    notify: Install docker-compose
 
  - name: start docker service and enable
    service: name=docker state=started enabled=yes
  
  - name: build.latest #check if exist
    stat: 
      path: build.latest
    register: stat_result
    
  - name: Copy Files for docker-compose proxy build
    copy:
      src: "{{ dcSource }}"
      dest: ~
      owner: ec2-user
      mode: '0600'
    
 # - name: Clear docker-compose
   # shell: build=$(cat build.latest) docker-compose down --rmi all      
   # when: stat_result.exists
    
 # - name: Start docker-compose
   # shell: |
       # build={{ build }} docker-compose up -d
       # echo {{ build }} > build.latest

  handlers:
  - name: Install docker-compose
    shell: |
       usermod -aG docker $USER
       curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
       chmod +x /usr/local/bin/docker-compose
