services:
    calc: "${repo}:${build}"
        container_name: calc
        ports:
            - 3000:3000
    proxy:
        build: "${proxyFolder}"
        container_name: proxy
        ports:
        - 80:80
        links:
        - calc