AWSTemplateFormatVersion: 2010-09-09
Description: EC 2 Instance template
Resources:
  DockerDeploy:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-083ebc5a49573896a
      KeyName: AWSKeyPair
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: DockerDeploy
      SecurityGroups:
        - !Ref DockerSGSshWeb
  DockerSGSshWeb:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: allow connections from SSH and Web
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0