pipeline {
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/voiddp/javascript-calculator.git'
      }
    }
    stage('Files in Build') {
      steps {
          sh 'chmod +x ./Jenkins-setup/build.sh'
		  sh './Jenkins-setup/build.sh'
      }
    }
	stage('Buld image with docker') {
      steps {
	   sh 'docker build -t "nginx-calc:Jenkins-setup/Dockerfile"'
      }
    }
	
  }
}
