pipeline {
	environment {
		registry = 'voiddp/nginx-calc'
		registryCredential = 'dockerhub'
		dockerImage = ''
		serverDeploy = '18.191.231.44'
	}
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/voiddp/javascript-calculator.git'
      }
    }
    stage('Processing Files') {
      steps {
          sh 'chmod +x ./Jenkins-setup/*.sh'
		  sh './Jenkins-setup/build.sh'
      }
    }
	stage('Bulding Image') {
      steps {
	   sh 'docker build -t "$registry:$BUILD_NUMBER" -f ./Jenkins-setup/Dockerfile .'
      }
    }	
	stage('Push to Hub') {
      steps {
		script {			
			docker.withRegistry( '', registryCredential ) {
				docker.image('$registry:$BUILD_NUMBER').push()
			}
		}
		sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
	stage('Deploy to EC2') {
		steps {
			sshagent(['jenkins-ec2']) {
				sh "ssh ec2-user@$serverDeploy 'bash -s' < deploy.sh calc $registry $BUILD_NUMBER"
			}
		}
	}
  }
}
