pipeline {
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/voiddp/javascript-calculator.git'
      }
    }
    stage('Files in Build') {
      steps {
          sh 'chmod +x ./Jenkins-setup/build.sh'
		  sh './Jenkins-setup/build.sh'
      }
    }
  }
}
